### PR TITLE
Use CakePHP v3.

### PR DESCRIPTION
**Pull request by ADmad**
I hope someone can take care of making necessary changes for deploying. I just started off using a fresh skeleton app and am not familiar with dokku.

Here's what it looks like
screen shot 2018-01-18 at 19 11 28

### CODE REVIEW

**Comment by josegonzalez** [comment]
@ADmad you can take the `Procfile` from the cakepackages repository and it should be a+ to deploy.

**Comment by markstory** [comment]
Pull request is too big to review, but the screenshot looks good :+1:

**Comment by ADmad** [comment]
@josegonzalez I copied the `Procfile` from `plugins.cakephp.org` repo. Anything else to be done? Are the deploying instructions in existing README still accurate?

@markstory I just started with fresh app skeleton, created
https://github.com/cakephp/inflector.cakephp.org/pull/8/files#diff-b724a0d928d85cc36a7ce95fdacfd9a4
https://github.com/cakephp/inflector.cakephp.org/pull/8/files#diff-6937bc974fb41d45dcae47dae9c7ef67
and updated routes.

**Comment by josegonzalez** [comment]
Merge and push should be fine.

**Pull request merged**
